### ISSUE TITLE
Can choose font but vault not affected (Android) 

### ISSUE THREAD

**Issue by proteusblack** [pourmand1376/obsidian-custom-font#1]
I was able to choose my font after installing the ttf into the created fonts folder. But the font over the vault is still default. I've tried restarting Obsidian but no change. I have also cleared every other font field that other plugins might set. The font is Arima (from Google Fonts). I'm on Android, and using the latest public Obsidian mobile build.

**Comment by pourmand1376** [comment]
Hi, Can you upload your font here so that I can test it?

**Comment by proteusblack** [comment]
> Hi, Can you upload your font here so that I can test it?

I've discovered that the Minimal theme is overriding this plugin's setting. I was using Minimal during the testing and when switching to default theme, the custom font worked.

**Comment by jwliles** [comment]
Based on my experience, using any community theme prevents the custom font from applying.

**Comment by pourmand1376** [comment]
> Based on my experience, using any community theme prevents the custom font from applying.

Can you name a community theme that does this? I want to test it and fix it.

**Comment by pourmand1376** [comment]
This should be fixed now. Update your plugin and check `Force Style`. 

![image](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/f27ea322-5904-4a38-879e-c8365173a3ab)
