### ISSUE TITLE
Font not visible/loading as iPad/iPhone (iPadOS/iOS)

### ISSUE THREAD

**Issue by Mibeon** [pourmand1376/obsidian-custom-font#14]
Downloaded the plugin, put the fonts in the ./obsidian/fonts directory on my iCloud vault.

Nothing happens. Nothing works. No matter which format (ttf, woff2).
Changed the folder name, changed the location completely from hidden to visible one (without ".") - nothing happens.

Currently this plugin just does nothing on iPad/iPhone.

**Comment by pourmand1376** [comment]
Hey @Mibeon ,

Fonts should be placed in your vaults folder. Where do you place it? 

Here's what I propose. Go to plugin and type the folder name as fonts. 

![CleanShot 2024-07-11 at 14 11 31@2x](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/f7cec111-6faf-458a-b037-0e35934675df)

Then hit `reload` and then go to your `fonts` folder in obsidian which is automatically created for you. 

Then, you should somehow paste the font you want into the folder. In my case it is mac (I've tested this one on windows, linux and android too: so I suppose it shouldn't have any problem on IPhone).

![CleanShot 2024-07-11 at 14 13 46@2x](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/08e04cd8-3f47-4e82-9498-4b4ba6e449a5)

Now, If you go back to your plugin and hit reload. It should show you something like this:

![CleanShot 2024-07-11 at 14 15 07@2x](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/4a24e7f3-bc30-47f3-822f-014742eb3a28)

**Comment by Mibeon** [comment]
Hey, thanks for the response.

It works. But with that solution I get a "fonts" folder right in my main vault. This is not, what really wanted. But generally it works.

Thank you!

**Comment by pourmand1376** [comment]
Hey, I'm happy that it works. 

To hide the folder from sight, you need to go to `your_vault_folder/.obsidian`. 

Unfortunately. As it is a hidden folder in most operating systems, you need to find a way to go inside it. 

Then you need to create a folder called `fonts` in that folder and put your font there. 


Then you could go into the obsidian plugin and make the folder name empty (actually the default value is `.obsidian/fonts/`. 

You should now see the fonts inside your folder after hitting reload button.

The real problem might be going inside `.obsidian` folder which you should find your way inside.
