### ISSUE TITLE
change font for windows platform

### ISSUE THREAD

**Issue by raoufix** [pourmand1376/obsidian-custom-font#17]
سلام ، امکان تغییر فونت در سیستم عامل ویندوز وجود نداره؟
چون من پوشه .obsidian/fonts رو اصلا توی ویندوز پیدا نمیکنم که فونت رو واردش کنم !!!!

**Comment by pourmand1376** [comment]
سلام. وقت شما بخیر. 

چند تا نکته به نظرم می‌رسه:
اول این که اگر فقط ویندوز استفاده می‌کنید اصلاً نیازی به استفاده از این پلاگین نیست. و میتونید تو تنظیمات خود obsidian فونت رو تغییر بدید. اصل قضیه این پلاگین برای اندروید و IOS و سیستم عامل هایی هست که نصب فونت روی اونها کار سختی هست. 

دوم این که پوشه اش پنهان هست. کلا پوشه‌هایی که با نقطه شروع میشن پنهان هستند. و باید تو تنظیمات پوشه ویندوز تیک فعال‌سازی فولدرهای مخفی رو بزنید. و بعد می‌تونید اون پوشه ها رو ببینید. 

سوم این که باز هم اگر خواستید از این پلاگین استفاده کنید و نمی‌خواهید به تنظیمات پوشه سیستم عامل دست بزنید، می‌تونید تو تنظیمات پلاگین به جای ``.obsdian/fonts` بنویسید `fonts`.

پلاگین بصورت اتوماتیک یک پوشه با همین نام براتون درست می‌کنه. و شما کافیه که فونت هاتون رو داخل این پوشه قرار بدید و ازش استفاده کنید.
