### ISSUE TITLE
Set font per page

### ISSUE THREAD

**Issue by diatche** [pourmand1376/obsidian-custom-font#7]
Thanks for writing this. This helps me to display Church Slavonic text correctly. The problem is that I only need the font loaded in those files which use Church Slavonic. So it would be great if there was a way to specify the font per file. 

Using the `font` property seems like a great way to set the font per page, instead of setting the font globally.

**Comment by pourmand1376** [comment]
This is easy. First, Use Custom CSS style and define it like this:
```css
.custom-font * {
font-family: YourFontName !important;
}
```
Then, you can set this `custom-font` CSS style in any file you want. 

You just need to set `cssclasses` in the frontmatter to `custom-font`. Something like this:

![image](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/5a7f4ad8-ba68-4d60-b011-3b12b16c813c)

And this is the settings page: 
![image](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/efc40b54-7c18-457e-801b-aed8d9b6e191)

**Comment by wildefae** [comment]
Just to check (because I know CSS, but not WELL) -- is it possible to create several different defined classes here for each different font, on the off chance I end up wanting to use a couple different fonts but only for certain things? (I can think of some use cases since I do writing/roleplaying/mood boards etc and could use handwriting fonts for example.) 

If in the Custom CSS style, I also defined .custom-font2 and .customfont3, etc etc (or .whatevername) with an additional font-family, and labeled them in the css-class front matter, would it let me use multiple fonts on a page by page basis?

**Comment by pourmand1376** [comment]
Yes, This should be okay in theory. But, currently my plugin only loads one external font. For this to work, I should work on #2.

**Comment by wildefae** [comment]
That would be awesome and much appreciated!

**Comment by pourmand1376** [comment]
This is now added. You can easily do what you want by using custom css classes.

**Comment by wildefae** [comment]
Thank you so much!!

**Comment by diatche** [comment]
It works great! Thank you

**Comment by Rick1029** [comment]
Hi, using the multiple font options to try to set a bigger font size and different font for Arabic only notes, it all works an doesn't alter the font of my notes unless I have "custom-font" written.

![image](https://github.com/pourmand1376/obsidian-custom-font/assets/62437512/35c39c14-ff8a-4a2a-a919-9fb70880cfb0)

However doing this makes Obsidian freak out as the plugin says it is "processing fonts" and it gets so slow you'd think it froze, but things just take 5-10 seconds to happen. It goes back to normal when you quit and restart and it works fine. It freezes again if you open the plugin settings menu and you have to _slowly_ change fonts, quit, then restart. I notice in the background when you open the plugin settings your font scrolls through every single one you have installed (I have five for Arabic) then settles on the one you selected, and unfreezes, unless you try picking a new one where it freezes until you reopen Obsidian.

**Comment by Ske-Man1149** [comment]
> Hi, using the multiple font options to try to set a bigger font size and different font for Arabic only notes, it all works an doesn't alter the font of my notes unless I have "custom-font" written.
> 
> ![image](https://github.com/pourmand1376/obsidian-custom-font/assets/62437512/35c39c14-ff8a-4a2a-a919-9fb70880cfb0)
> 
> However doing this makes Obsidian freak out as the plugin says it is "processing fonts" and it gets so slow you'd think it froze, but things just take 5-10 seconds to happen. It goes back to normal when you quit and restart and it works fine. It freezes again if you open the plugin settings menu and you have to _slowly_ change fonts, quit, then restart. I notice in the background when you open the plugin settings your font scrolls through every single one you have installed (I have five for Arabic) then settles on the one you selected, and unfreezes, unless you try picking a new one where it freezes until you reopen Obsidian.

@pourmand1376 we want an answer,

**Comment by pourmand1376** [comment]
Hi. Thanks you for mentioning it. 

This is the problem I've been aware of. I don't know any solutions. 

I'll create a new issue for it in case anyone knows how to fix this bug.

**Comment by nathgit** [comment]
This doesn't apply the custom font I set. it just shows default, as if I didn't have a font set at all.
