### ISSUE TITLE
How to set a bold font in text

### ISSUE THREAD

**Issue by Rainbow132** [pourmand1376/obsidian-custom-font#8]
![图片](https://github.com/pourmand1376/obsidian-custom-font/assets/37493165/e0817807-c332-4a13-81f9-a35c98b0dccc)
As shown in the picture, it is still the default font. Could this be the reason for my font?

**Comment by pourmand1376** [comment]
Can you provide more information on how you configured plugin?

**Comment by Rainbow132** [comment]
![图片](https://github.com/pourmand1376/obsidian-custom-font/assets/37493165/2981e3ec-0e41-4008-9829-fc559401a443)
This is my plugin configuration, can you share your font for me to try, because I tried other fonts and the same thing happened。
